/**
 * Created by roderickWang on 7/26/15.
 */
export const ModalTypes= {
    SCHEME_ADAPT_SHOPS:'SHCEME_ADAPT_SHOPS',
    SHOP_CONTACTORS:'SHOP_CONTACTORS',
    SELECT_CONTRACT:'SELECT_CONTRACT',
    ERROR_INFO:'ERROR_INFO',
    DEL_SHOP_IN_ALL:'DEL_SHOP_IN_ALL',
    SELECT_GUARANTEE:'SELECT_GUARANTEE',
    TRANSFER_SALER:'TRANSFER_SALER',
    LOADING:"LOADING"
}
